# Generated by Django 2.2.7 on 2019-12-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191215_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
