# Generated by Django 2.2.7 on 2020-01-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames_receiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
